
use pandasdb;
show tables;
describe customer_behavior;

-- What is the total revenue generated by male vs. female customers?
select gender, SUM(purchase_amount) as revenve
from customer_behavior
group by gender;

-- Which customers used a discount but still spent more than the average purchase amount?
select customer_id, purchase_amount
from customer_behavior
where discount_applied = 'yes' and purchase_amount >= (select AVG(purchase_amount) from customer_behavior);

-- Which are the top 5 products with the highest average review rating?
select item_purchased, round(AVG(review_rating),2) as "Average Product Rating"
from customer_behavior
group by item_purchased
order by avg(review_rating) desc
limit 5;

-- Compare the average Purchase Amounts between Standard and Express Shipping.
Select shipping_type,
round(avg(purchase_amount),2)
from customer_behavior
where shipping_type in ('standard','Express')
group by shipping_type;

-- Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
select subscription_status,
Count(customer_id) as total_customers,
round(AVG(purchase_amount),2) as avg_spend,
round(SUM(purchase_amount),2) as total_revenue
from customer_behavior
group by subscription_status
order by total_revenue, avg_spend desc;

-- Which 5 products have the highest percentage of purchases with discounts applied?
SELECT item_purchased,
ROUND(100 * SUM(CASE WHEN discount_applied = 'yes' THEN 1 ELSE 0 END) / COUNT(*),2) AS discount_rate
FROM customer_behavior
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;


-- Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.
SELECT CASE
WHEN previous_purchases = 1 THEN 'New'
WHEN previous_purchases <= 10 THEN 'Returning'
ELSE 'Loyal'
END AS customer_segment,
COUNT(*) AS "Number of Customers"
FROM customer_behavior
GROUP BY customer_segment;


-- What are the top 3 most purchased products within each category?
SELECT * FROM (
SELECT category, item_purchased,
COUNT(customer_id) AS total_orders,
ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
FROM customer_behavior
GROUP BY category, item_purchased) 
ranked_items
WHERE item_rank <= 3;


-- Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status,
COUNT(customer_id) AS Repeat_buyers
FROM customer_behavior
WHERE previous_purchases > 5
GROUP BY subscription_status;


-- What is the revenue contribution of each age group?
Select age_group,
SUM(purchase_amount) as total_revenue
from customer_behavior
group by age_group
order by total_revenue desc;




